[package]
name = "yetanotherclown/threadpool"
description = "A library for creating Thread Pools to improve performance and reduce latency."
version = "1.0.0"
license = "MIT"
authors = ["YetAnotherClown"]
realm = "shared"
registry = "https://github.com/upliftgames/wally-index"
exclude = ["**"]
include = ["lib", "lib/*", "default.project.json", "wally.toml", "wally.lock"]